/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pers.jasonLbase.avro.example.codec.complexRecord;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Team extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6702953125882209137L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Team\",\"namespace\":\"pers.jasonLbase.avro.example.codec.complexRecord\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"members\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Member\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"name\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Team> ENCODER =
      new BinaryMessageEncoder<Team>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Team> DECODER =
      new BinaryMessageDecoder<Team>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Team> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Team> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Team>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Team to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Team from a ByteBuffer. */
  public static Team fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.util.List<pers.jasonLbase.avro.example.codec.complexRecord.Member> members;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Team() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param members The new value for members
   */
  public Team(java.lang.CharSequence name, java.util.List<pers.jasonLbase.avro.example.codec.complexRecord.Member> members) {
    this.name = name;
    this.members = members;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return members;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: members = (java.util.List<pers.jasonLbase.avro.example.codec.complexRecord.Member>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'members' field.
   * @return The value of the 'members' field.
   */
  public java.util.List<pers.jasonLbase.avro.example.codec.complexRecord.Member> getMembers() {
    return members;
  }

  /**
   * Sets the value of the 'members' field.
   * @param value the value to set.
   */
  public void setMembers(java.util.List<pers.jasonLbase.avro.example.codec.complexRecord.Member> value) {
    this.members = value;
  }

  /**
   * Creates a new Team RecordBuilder.
   * @return A new Team RecordBuilder
   */
  public static pers.jasonLbase.avro.example.codec.complexRecord.Team.Builder newBuilder() {
    return new pers.jasonLbase.avro.example.codec.complexRecord.Team.Builder();
  }

  /**
   * Creates a new Team RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Team RecordBuilder
   */
  public static pers.jasonLbase.avro.example.codec.complexRecord.Team.Builder newBuilder(pers.jasonLbase.avro.example.codec.complexRecord.Team.Builder other) {
    return new pers.jasonLbase.avro.example.codec.complexRecord.Team.Builder(other);
  }

  /**
   * Creates a new Team RecordBuilder by copying an existing Team instance.
   * @param other The existing instance to copy.
   * @return A new Team RecordBuilder
   */
  public static pers.jasonLbase.avro.example.codec.complexRecord.Team.Builder newBuilder(pers.jasonLbase.avro.example.codec.complexRecord.Team other) {
    return new pers.jasonLbase.avro.example.codec.complexRecord.Team.Builder(other);
  }

  /**
   * RecordBuilder for Team instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Team>
    implements org.apache.avro.data.RecordBuilder<Team> {

    private java.lang.CharSequence name;
    private java.util.List<pers.jasonLbase.avro.example.codec.complexRecord.Member> members;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(pers.jasonLbase.avro.example.codec.complexRecord.Team.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.members)) {
        this.members = data().deepCopy(fields()[1].schema(), other.members);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Team instance
     * @param other The existing instance to copy.
     */
    private Builder(pers.jasonLbase.avro.example.codec.complexRecord.Team other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.members)) {
        this.members = data().deepCopy(fields()[1].schema(), other.members);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public pers.jasonLbase.avro.example.codec.complexRecord.Team.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public pers.jasonLbase.avro.example.codec.complexRecord.Team.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'members' field.
      * @return The value.
      */
    public java.util.List<pers.jasonLbase.avro.example.codec.complexRecord.Member> getMembers() {
      return members;
    }

    /**
      * Sets the value of the 'members' field.
      * @param value The value of 'members'.
      * @return This builder.
      */
    public pers.jasonLbase.avro.example.codec.complexRecord.Team.Builder setMembers(java.util.List<pers.jasonLbase.avro.example.codec.complexRecord.Member> value) {
      validate(fields()[1], value);
      this.members = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'members' field has been set.
      * @return True if the 'members' field has been set, false otherwise.
      */
    public boolean hasMembers() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'members' field.
      * @return This builder.
      */
    public pers.jasonLbase.avro.example.codec.complexRecord.Team.Builder clearMembers() {
      members = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Team build() {
      try {
        Team record = new Team();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.members = fieldSetFlags()[1] ? this.members : (java.util.List<pers.jasonLbase.avro.example.codec.complexRecord.Member>) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Team>
    WRITER$ = (org.apache.avro.io.DatumWriter<Team>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Team>
    READER$ = (org.apache.avro.io.DatumReader<Team>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
