package pers.jasonLbase.parquet.example;

import java.util.Date;
import java.util.Random;

public class OrgEventSysTraffic {
	private static long oidCount = 1L;
	static private int intCount;
	private int intCount1;
	private int intCount2;
	private int intCount256;
	
	public Long oid;
	public Long collectorOid;
	public Long eventTime;
	public Long recvTime;
	public int eventLevel;
	public int eventMainType;
	public int eventType;
	public String eventName;
	public String eventOrgID;
	public long eventCount;
	public long deviceOid;
	public String srcIP;
	public long srcIPInt;
	public int srcNetType;
	public int srcPort;
	public String srcCountryCode;
	public String srcDomain;
	public String srcSSID;
	public String srcMac;
	public String srcUUID;
	public String masterSrcMAC;
	public String srcDevType;
	public String OSName;
	public String OSVersion;
	public String dstIP;
	public long dstIPInt;
	public int dstNetType;
	public int dstPort;
	public String dstCountryCode;
	public String dstDomain;
	public String dstSSID;
	public String dstUUID;
	public String protocol;
	public String service;
	public String sessionId;
	public String virus;
	public String virusId;
	public String filename;
	public String sha256;
	public int analyticsSubmit;
	public String analyticsCksum;
	public String attack;
	public String attackId;
	public String appId;
	public String app;
	public String appCat;
	public String appProfile;
	public String appAct;
	public int appRisk;
	public String hostName;
	public String catDesc;
	public String sender;
	public String recipient;
	public int mailCount;
	public int spamCount;
	public String DLPRule;
	public String HTTPStatus;
	public String URLCnt;
	public String DLPProfile;
	public String DLPArchive;
	public String tranDisp;
	public String dirDisp;
	public String tranIP;
	public int tranPort;
	public String tranSIP;
	public int tranSPort;
	public long centralNatId;
	public int shaperDropSentByte;
	public int shaperDropRcvdByte;
	public int shaperPerIPDropByte;
	public String shaperSentName;
	public String shaperRcvdName;
	public String shaperPerIPName;
	public String VPN;
	public String VPNType;
	public String VPNTunnel;
	public long WANIn;
	public long WANOut;
	public long LANIn;
	public long LANOut;
	public String UTMEvent;
	public String UTMSubType;
	public String UTMSeverity;
	public String UTMAction;
	public String ap;
	public String apSN;
	public long channel;
	public String radioBand;
	public String action;
	public String rule;
	public String WANOptAppType;
	public long duration;
	public long sentByte;
	public long rcvdByte;
	public int sentPkt;
	public int rcvdPkt;
	public String VDom;
	public String srcInterface;
	public String dstInterface;
	public int policyId;
	public String policyUUID;
	public String identIdx;
	public String userId;
	public String groupId;
	public String unauthUser;
	public String unauthUserSrc;
	public long CRScore;
	public String CRLevel;
	public long CRAction;
	public int countApp;
	public int countAV;
	public int countDlp;
	public int countIPS;
	public int countWAF;
	public int countWeb;
	public int resvCount1;
	public int resvCount2;
	public int resvCount3;
	public int resvCount4;
	public int resvCount5;
	public String longComment;
	public String eventPar;
	public String resvIP1;
	public long resvIPInt1;
	public String resvIP2;
	public long resvIPInt2;
	public String resvIP3;
	public long resvIPInt3;
	public String resvIP4;
	public long resvIPInt4;
	public String resvIP5;
	public long resvIPInt5;
	public long resvInt1;
	public long resvInt2;
	public long resvInt3;
	public long resvInt4;
	public long resvInt5;
	public String resvStr1;
	public String resvStr2;
	public String resvStr3;
	public String resvStr4;
	public String resvStr5;
	public int regionOidFoo;
	public long eventDateFoo;
	public int regionOid;
	public long eventDate;
	

	
	public OrgEventSysTraffic() {
		intCount++;
		intCount1 = intCount+2;
		intCount2 = intCount+3;
		intCount256 = intCount % 255;
		
		this.oid = oidCount++;
		this.collectorOid = this.oid;
		this.recvTime = 1527501665000L;
		this.eventTime = 1527501665000L;
		this.eventLevel = 1;
		this.eventMainType = intCount256;
		this.eventType = 1;
		this.eventName = "eventName" + this.oid;
		this.eventOrgID = "eventOrgID" + this.oid;
		this.eventCount = 1;
		this.deviceOid = 1;
		this.srcIP = "1.1.1." + intCount256;
		this.srcIPInt = 0L;
		this.srcNetType = 1;
		this.srcPort = intCount256;
		this.srcCountryCode = "srcCountryCode" + intCount256;
		this.srcDomain = "srcDomain" + intCount;
		this.srcSSID = "srcSSID" + intCount;
		this.srcMac = "srcMac" + intCount;
		this.srcUUID = "srcUUID" + intCount;
		this.masterSrcMAC = "masterSrcMAC" + intCount;
		this.srcDevType = "srcDevType" + intCount;
		this.OSName = "OSName" + intCount;
		this.OSVersion = "OSVersion" + intCount;
		this.dstIP = "2.2.2." + intCount;
		this.dstIPInt = 0L;
		this.dstNetType = intCount;
		this.dstPort = intCount;
		this.dstCountryCode = "Code" + intCount;
		this.dstDomain = "Domain" + intCount;
		this.dstSSID = "dstSSID" + intCount;
		this.dstUUID = "dstUUID" + intCount;
		this.protocol = "protocol" + intCount;
		this.service = "service" + intCount;
		this.sessionId = "sessionId" + intCount;
		this.virus = "virus" + intCount;
		this.virusId = "virusId" + intCount;
		this.filename = "filename" + intCount;
		this.sha256 = "sha256" + intCount;
		this.analyticsSubmit = intCount1;
		this.analyticsCksum = "analyticsCksum" + intCount;
		this.attack = "attack" + intCount;
		this.attackId = "attackId" + intCount;
		this.appId = "appId" + intCount;
		this.app = "app" + intCount;
		this.appCat = "appCat" + intCount;
		this.appProfile = "appProfile" + intCount;
		this.appAct = "appAct" + intCount;
		this.appRisk = intCount1;
		this.hostName = "hostName" + intCount;
		this.catDesc = "catDesc" + intCount;
		this.sender = "sender" + intCount;
		this.recipient = "recipient" + intCount;
		this.mailCount = intCount;
		this.spamCount = intCount;
		this.DLPRule = "dlprule" + intCount;
		this.HTTPStatus = "HTTPStatus" + intCount;
		this.URLCnt = "URLCnt" + intCount;
		this.DLPProfile = "DLPProfile" + intCount;
		this.DLPArchive = "DLPArchive" + intCount;
		this.tranDisp = "tranDisp" + intCount;
		this.dirDisp = "dirDisp" + intCount;
		this.tranIP = "tranIP" + intCount;
		this.tranPort = intCount1;
		this.tranSIP = "tranSIP" + intCount;
		this.tranSPort = intCount2;
		this.centralNatId = this.oid;
		this.shaperDropSentByte = intCount1;
		this.shaperDropRcvdByte = intCount2;
		this.shaperPerIPDropByte = intCount1;
		this.shaperSentName = "shaperSentName" + intCount;
		this.shaperRcvdName = "shaperRcvdName" + intCount;
		this.shaperPerIPName = "shaperPerIPName" + intCount;
		this.VPN = "VPN" + intCount;
		this.VPNType = "VPNType" + intCount;
		this.VPNTunnel = "VPNTunnel" + intCount;
		this.WANIn = this.oid;
		this.WANOut = this.oid;
		this.LANIn = this.oid;
		this.LANOut = this.oid;
		this.UTMEvent = "UTMEvent" + intCount;
		this.UTMSubType = "UTMSubType" + intCount;
		this.UTMSeverity = "UTMSeverity" + intCount;
		this.UTMAction = "UTMAction" + intCount;
		this.ap = "ap" + intCount;
		this.apSN = "apSN" + intCount;
		this.channel = this.oid;
		this.radioBand = "radioBand" + intCount;
		this.action = "action" + intCount;
		this.rule = "rule" + intCount;
		this.WANOptAppType = "WANOptAppType" + intCount;
		this.duration = intCount+1;
		this.sentByte = intCount+2;
		this.rcvdByte = intCount+3;
		this.sentPkt = intCount+4;
		this.rcvdPkt = intCount+5;
		this.VDom = "VDom" + intCount;
		this.srcInterface = "srcInterface" + intCount;
		this.dstInterface = "srcInterface" + intCount;
		this.policyId = intCount;
		this.policyUUID = "policyUUID";
		this.identIdx = "identIdx";
		this.userId = "userId" + intCount;
		this.groupId = "groupId" + intCount;
		this.unauthUser = "unauthUser" + intCount;
		this.unauthUserSrc = "unauthUserSrc" + intCount;
		this.CRScore = this.oid+1;
		this.CRLevel = "CRLevel" + intCount;
		this.CRAction = intCount1;
		this.countApp = intCount2;
		this.countAV = intCount1;
		this.countDlp = intCount2;
		this.countIPS = intCount2;
		this.countWAF = intCount1;
		this.countWeb = intCount2;
		this.resvCount1 = 0;
		this.resvCount2 = 0;
		this.resvCount3 = 0;
		this.resvCount4 = 0;
		this.resvCount5 = 0;
		this.longComment = "longComment abcdefghijklmnopqrstuvwxyz" + intCount;
		this.eventPar = "";
		this.resvIP1 = "";
		this.resvIPInt1 = 0L;
		this.resvIP2 = "";
		this.resvIPInt2 = 0L;
		this.resvIP3 = "";
		this.resvIPInt3 = 0L;
		this.resvIP4 = "";
		this.resvIPInt4 = 0L;
		this.resvIP5 = "";
		this.resvIPInt5 = 0L;
		this.resvInt1 = 0L;
		this.resvInt2 = 0L;
		this.resvInt3 = 0L;
		this.resvInt4 = 0L;
		this.resvInt5 = 0L;
		this.resvStr1 = "";
		this.resvStr2 = "";
		this.resvStr3 = "";
		this.resvStr4 = "";
		this.resvStr5 = "";
		this.regionOidFoo = 99;
		this.eventDateFoo = 1527501600L;
		this.regionOid = 99;
		this.eventDate = 1527501600L;
	}

}
